### ISSUE TITLE
Networking

### ISSUE THREAD

**Issue by Euheimr** [jacobbetz/techiton-game#6]
# Mind maps:
  * Techiton Service Architecture: https://mm.tt/1303597775?t=CxgiFRo2bc

*Mirror is a high level Networking API for Unity, built on top of the low level Telepathy library.*
  * https://github.com/vis2k/Mirror

[FizzySteamyMirror](https://github.com/FizzCube/FizzySteamyMirror)
  * Fizzcube bringing together Steam and Mirror.
  * Version 2, complete rebuild utilising Async (Previously SteamNetNetworkTransport) of a Steam P2P network transport layer for Mirror - 2018 branch (vis2k's UNET replacement for Unity)
  * FizzySteamyMirror uses Steamworks.NET wrapper for the steamworks API.

# Server:
## [Valve Sockets C#](https://github.com/nxrighthere/ValveSockets-CSharp)

[Nakama](https://github.com/heroiclabs/nakama) | [Unity store link](https://assetstore.unity.com/packages/tools/network/nakama-81338) (Distributed server for social and realtime games and apps.)
* [Nakama docs](https://heroiclabs.com/docs)
  * [Recommended prod settings](https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html)
  * [Deployment notes](https://github.com/heroiclabs/nakama#deployment)

# DB:
[cockroachdb](https://github.com/cockroachdb/cockroach)
* [cockroachdb docs](https://www.cockroachlabs.com/docs/stable/)
* [hardware reqs](https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#basic-hardware-recommendations)

# Lockstep research:
[1500 Archers on a 28.8: Network Programming in Age of Empires and Beyond(2001)](https://www.gamasutra.com/view/feature/131503/1500_archers_on_a_288_network_.php)

## https://github.com/euheimr/LockstepFramework
Start with modeling this ^

## In-Depth Lockstep Explanation [(src)](https://gamedev.stackexchange.com/questions/90735/in-depth-lockstep-explanation)
You need to have a future command queue that will only be acted upon once all parties will have confirmed reception of the command.

* This queue will include no-operation null commands if no new command is to be executed.

* The delay for each command can be dependent on the ping/lag.

* The simulation on every peer only executes to the point (call it frame number, time, or step) where all commands have been confirmed as received so every peer will execute the same thing at the same time.

* So let's say the step granularity is every 100ms, got a 175ms max network ping, we're at 332ms, the user click to move a unit, we send a packet "#N: unit A move to XY at 600ms" (332 rounded up to 400ms + rounded up ping to 200ms).

* So long as a reply from all peers comes in saying "Packet #N Confirmed" before game time 600ms the game wont need to wait, if we don't receive confirmation we hold the game simulation and we resend the command packet every N ms (don't flood the network) until we get confirmation.

* We also need to receive command packets from all peers for all steps, even if there are no commands send a no-command sync packet eg: "Nothing to do at 700ms".

* "Confirmation of the confirmation" is simply the next command packet which is only sent if the peer has received confirmation of its previous packet, it will resend its previous command if no confirmation arrives until it gets a confirmation (or a time out and the connection is considered lost).

* Confirmation can be sent as part of the next command packet to reduce traffic by increasing the queue to 2 commands with half the time (same lag overall, half the packets).

* From there a lot can be added such as variable lag/ping detection/adjustments, prediction and rollbacks, etc, to reduce the perceived network lag.

Valve 
  * [Latency Compensating Methods in Client/Server In-game Protocol Design and Optimization (2001)](https://developer.valvesoftware.com/wiki/Latency_Compensating_Methods_in_Client/Server_In-game_Protocol_Design_and_Optimization)
  * [Client-side prediction](https://developer.valvesoftware.com/wiki/Latency_Compensating_Methods_in_Client/Server_In-game_Protocol_Design_and_Optimization#Client_Side_Prediction)

# TODO:
- [ ] [Steam API integration](https://partner.steamgames.com/doc/features/multiplayer/networking)
- [ ] [Game networking sockets]( https://github.com/jacobbetz/GameNetworkingSockets)
- [ ] Create game network lobby
  * [Unity asset (free) | Network lobby](https://assetstore.unity.com/packages/essentials/network-lobby-41836)
